name: 'Load Workflow Configuration'
description: 'Loads shared configuration values from workflow-config.yml'
outputs:
  config:
    description: 'The full configuration as a JSON string'
    value: ${{ steps.load-config.outputs.config }}
  project:
    description: 'Project name'
    value: ${{ steps.load-config.outputs.project }}
  main_branch:
    description: 'Main branch name'
    value: ${{ steps.load-config.outputs.main_branch }}
  docs_branch:
    description: 'Documentation branch name'
    value: ${{ steps.load-config.outputs.docs_branch }}
  version:
    description: 'Current version string'
    value: ${{ steps.load-config.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Load Configuration
      id: load-config
      shell: bash
      run: |
        echo "Loading workflow configuration..."
        
        # Check if the config file exists
        if [ ! -f ".github/workflow-config.yml" ]; then
          echo "Error: workflow-config.yml not found"
          exit 1
        fi
        
        # Read the configuration file and convert to JSON
        CONFIG=$(yq -o=json '.version' .github/workflow-config.yml)
        echo "config=$CONFIG" >> $GITHUB_OUTPUT
        
        # Extract specific values needed by most workflows
        PROJECT=$(yq '.build.project' .github/workflow-config.yml)
        MAIN_BRANCH=$(yq '.repository.main_branch' .github/workflow-config.yml)
        DOCS_BRANCH=$(yq '.repository.docs_branch' .github/workflow-config.yml)
        
        # Create version string
        MAJOR=$(yq '.version.major' .github/workflow-config.yml)
        MINOR=$(yq '.version.minor' .github/workflow-config.yml)
        PATCH=$(yq '.version.patch' .github/workflow-config.yml)
        VERSION="$MAJOR.$MINOR.$PATCH"
        
        # Output key values
        echo "project=$PROJECT" >> $GITHUB_OUTPUT
        echo "main_branch=$MAIN_BRANCH" >> $GITHUB_OUTPUT
        echo "docs_branch=$DOCS_BRANCH" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        echo "Configuration loaded successfully" 