name: 'Disable Code Signing'
description: 'Disables code signing for CI builds in consistent manner across workflows'

runs:
  using: "composite"
  steps:
    - name: Create xcconfig file to disable code signing
      shell: bash
      run: |
        echo "Creating configuration to disable code signing..."
        echo "CODE_SIGN_IDENTITY = -" > ci_signing_disabled.xcconfig
        echo "CODE_SIGNING_REQUIRED = NO" >> ci_signing_disabled.xcconfig
        echo "CODE_SIGN_ENTITLEMENTS = " >> ci_signing_disabled.xcconfig
        echo "CODE_SIGNING_ALLOWED = NO" >> ci_signing_disabled.xcconfig
        echo "EXPANDED_CODE_SIGN_IDENTITY = -" >> ci_signing_disabled.xcconfig
        echo "EXPANDED_CODE_SIGN_IDENTITY_NAME = -" >> ci_signing_disabled.xcconfig
        echo "DEVELOPMENT_TEAM = " >> ci_signing_disabled.xcconfig
        echo "PROVISIONING_PROFILE_SPECIFIER = " >> ci_signing_disabled.xcconfig
        echo "Created xcconfig to disable code signing at: $(pwd)/ci_signing_disabled.xcconfig"

    - name: Modify Xcode project settings
      shell: bash
      run: |
        echo "Setting up to override code signing requirements..."
        
        # Create directory for Xcode-specific scripts if needed
        mkdir -p ~/.xcode-scripts
        
        # Create a simple script to directly modify project settings
        echo '#!/bin/bash' > ~/.xcode-scripts/disable_codesign.sh
        echo 'echo "Disabling code signing for Xcode builds"' >> ~/.xcode-scripts/disable_codesign.sh
        echo 'defaults write com.apple.dt.Xcode IDESkipCodeSigningVerification -bool YES' >> ~/.xcode-scripts/disable_codesign.sh
        echo 'defaults write com.apple.dt.Xcode IDESkipMacroValidation -bool YES' >> ~/.xcode-scripts/disable_codesign.sh
        
        # Make it executable
        chmod +x ~/.xcode-scripts/disable_codesign.sh
        
        # Run the script
        ~/.xcode-scripts/disable_codesign.sh

    - name: Export build environment variables
      shell: bash
      run: |
        # Export the path to the xcconfig file and other signing-related variables
        echo "DISABLE_SIGNING=true" >> $GITHUB_ENV
        echo "XCCONFIG_PATH=$(pwd)/ci_signing_disabled.xcconfig" >> $GITHUB_ENV
        echo "CODE_SIGN_IDENTITY=-" >> $GITHUB_ENV
        echo "CODE_SIGNING_REQUIRED=NO" >> $GITHUB_ENV
        echo "CODE_SIGN_ENTITLEMENTS=" >> $GITHUB_ENV
        echo "CODE_SIGNING_ALLOWED=NO" >> $GITHUB_ENV
        
        # Output help info for use in build commands
        echo ""
        echo "To disable code signing in xcodebuild commands, add these flags:"
        echo "xcodebuild [...] CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS= CODE_SIGNING_ALLOWED=NO"
        echo ""
        echo "To use the xcconfig file, add this flag:"
        echo "xcodebuild [...] -xcconfig \$XCCONFIG_PATH" 