name: 'Setup Swift on Ubuntu'
description: 'Sets up Swift environment on Ubuntu with support for different Ubuntu versions'

inputs:
  swift-version:
    description: 'Swift version to install'
    required: false
    default: '5.9'

runs:
  using: "composite"
  steps:
    - name: Detect Ubuntu version
      id: ubuntu-version
      shell: bash
      run: |
        UBUNTU_VERSION=$(lsb_release -rs)
        echo "ubuntu_version=$UBUNTU_VERSION" >> $GITHUB_OUTPUT
        echo "Detected Ubuntu version: $UBUNTU_VERSION"
        
        # Map newer Ubuntu versions to the closest supported version
        if [[ "$UBUNTU_VERSION" == "24.04" ]]; then
          echo "ubuntu_map_version=22.04" >> $GITHUB_OUTPUT
          echo "Using compatibility mapping: 24.04 -> 22.04"
        else
          echo "ubuntu_map_version=$UBUNTU_VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Install Swift dependencies
      shell: bash
      run: |
        echo "Installing Swift dependencies..."
        sudo apt-get update
        sudo apt-get install -y \
          binutils \
          git \
          gnupg2 \
          libc6-dev \
          libcurl4-openssl-dev \
          libedit2 \
          libgcc-9-dev \
          libpython3.8 \
          libsqlite3-0 \
          libstdc++-9-dev \
          libxml2-dev \
          libz3-dev \
          pkg-config \
          tzdata \
          unzip \
          zlib1g-dev

    - name: Download and install Swift
      shell: bash
      run: |
        SWIFT_VERSION=${{ inputs.swift-version }}
        UBUNTU_VERSION=${{ steps.ubuntu-version.outputs.ubuntu_map_version }}
        
        # Convert version format (e.g., 22.04 -> 2204)
        UBUNTU_VERSION_NO_DOTS=$(echo "$UBUNTU_VERSION" | tr -d '.')
        
        SWIFT_PACKAGE="swift-$SWIFT_VERSION-RELEASE-ubuntu$UBUNTU_VERSION_NO_DOTS"
        SWIFT_URL="https://download.swift.org/swift-$SWIFT_VERSION-release/ubuntu$UBUNTU_VERSION_NO_DOTS/swift-$SWIFT_VERSION-RELEASE/$SWIFT_PACKAGE.tar.gz"
        
        echo "Downloading Swift from: $SWIFT_URL"
        
        # Create a directory for the download
        mkdir -p /tmp/swift-download
        cd /tmp/swift-download
        
        # Download Swift with better error handling
        echo "Downloading Swift package..."
        if ! wget --no-verbose "$SWIFT_URL"; then
          echo "Failed to download Swift from $SWIFT_URL"
          echo "Trying alternative location..."
          
          # Try toolchains as a fallback
          ALT_URL="https://download.swift.org/swift-$SWIFT_VERSION-release/ubuntu$UBUNTU_VERSION_NO_DOTS/swift-$SWIFT_VERSION-RELEASE/swift-$SWIFT_VERSION-RELEASE-ubuntu$UBUNTU_VERSION_NO_DOTS.tar.gz"
          if ! wget --no-verbose "$ALT_URL"; then
            echo "Failed to download Swift from alternative location as well."
            echo "Attempting to download latest release instead..."
            
            # Try the latest version instead
            LATEST_URL="https://download.swift.org/swift-5.9.2-release/ubuntu$UBUNTU_VERSION_NO_DOTS/swift-5.9.2-RELEASE/swift-5.9.2-RELEASE-ubuntu$UBUNTU_VERSION_NO_DOTS.tar.gz"
            if ! wget --no-verbose "$LATEST_URL"; then
              echo "All download attempts failed. Aborting."
              exit 1
            else
              SWIFT_PACKAGE="swift-5.9.2-RELEASE-ubuntu$UBUNTU_VERSION_NO_DOTS"
            fi
          else
            echo "Alternative download successful."
          fi
        fi
        
        echo "Extracting Swift package..."
        # List the downloaded files for debugging
        ls -la
        
        # Extract Swift with better error handling
        if ! tar xzf $(ls *.tar.gz); then
          echo "Failed to extract Swift package."
          exit 1
        fi
        
        echo "Installing Swift..."
        # Check if the extracted package exists
        if [ ! -d "$SWIFT_PACKAGE" ]; then
          # Try to find any swift directory
          SWIFT_PACKAGE=$(find . -maxdepth 1 -type d -name "swift-*" | head -n 1)
          if [ -z "$SWIFT_PACKAGE" ]; then
            echo "Could not find extracted Swift package directory."
            exit 1
          fi
          # Remove the leading ./
          SWIFT_PACKAGE=${SWIFT_PACKAGE#./}
        fi
        
        # Move Swift to /usr/share and update PATH
        echo "Moving Swift to /usr/share/swift..."
        sudo mkdir -p /usr/share/swift
        sudo cp -R "$SWIFT_PACKAGE"/* /usr/share/swift/
        
        echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH
        
        # Verify installation
        echo "Swift installation complete. Attempting to verify..."
        export PATH="/usr/share/swift/usr/bin:$PATH"
        if command -v swift &> /dev/null; then
          swift --version
        else
          echo "Swift command not found in PATH after installation."
          echo "PATH is: $PATH"
          ls -la /usr/share/swift/usr/bin || echo "Swift bin directory not found"
        fi 