name: Artifact Test

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  test-workflow:
    runs-on: ubuntu-latest
    outputs:
      test-content: ${{ steps.create-content.outputs.content }}
      timestamp: ${{ steps.create-content.outputs.timestamp }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create test content
        id: create-content
        run: |
          echo "Creating test content without artifacts"
          CONTENT="This is test content created at $(date)"
          TIMESTAMP=$(date +%s)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "Content: $CONTENT"
          echo "Timestamp: $TIMESTAMP"
      
  use-output:
    needs: test-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Use test content from previous job
        run: |
          echo "Received content from previous job:"
          echo "${{ needs.test-workflow.outputs.test-content }}"
          echo "Created at timestamp: ${{ needs.test-workflow.outputs.timestamp }}" 