name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
permissions:
  contents: read
  pull-requests: write
    
jobs:
  label-pr:
    name: Analyze and Label PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run PR Labeler
        id: prlabeler
        uses: ./.github/actions/pr-labeler
      - name: Apply Labels
        uses: actions/github-script@v7
        env:
          LABELS_JSON: ${{ steps.prlabeler.outputs.labels }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = JSON.parse(process.env.LABELS_JSON || '[]');
            if (!labels || labels.length === 0) {
              console.log('No labels to apply');
              return;
            }
            console.log(`Applying labels: ${labels.join(', ')}`);
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });
            console.log('Labels applied successfully');
      - name: Add PR Comment with Analysis
        if: success()
        uses: actions/github-script@v7
        env:
          LABELS_JSON: ${{ steps.prlabeler.outputs.labels }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = JSON.parse(process.env.LABELS_JSON || '[]');
            if (!labels || labels.length === 0) {
              return;
            }
            const labelDescriptions = {
              'area/ui': 'UI changes that might require visual review',
              'area/core': 'Core functionality changes',
              'area/testing': 'Test additions or modifications',
              'area/documentation': 'Documentation updates',
              'area/ci': 'CI/CD workflow changes',
              'area/dependencies': 'Dependency updates',
              'area/metal': 'Metal shader or GPU-accelerated code changes that may require specialized review',
              'size/small': 'Small PR with limited scope',
              'size/medium': 'Medium sized PR with broader changes',
              'size/large': 'Large PR with significant changes'
            };
            let body = `## PR Analysis\n\nThis PR has been automatically labeled based on file changes:\n\n`;
            labels.forEach(label => {
              body += `- **${label}**: ${labelDescriptions[label] || 'No description available'}\n`;
            });
            body += `\n*Note: This is an automated analysis. Please verify the labels are correct.*`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            }); 